server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/blackholes0/springcloud-config.git
          search-paths:
            - springcloud-config
          username: blackholes0
          password: Liu19960221
      label: master

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka ,http://eureka7002.com:7002/eureka